const DAYS = [
  {day:1,week:1,title:"HTML Bilan Tanishuv",tech:"HTML",
   lesson:"HTML (HyperText Markup Language) — veb-saytning asosi. Barcha saytlar HTML bilan quriladi.",
   practice:"VS Code oching. index.html yarating. Birinchi HTML sahifangizni yozing.",
   code:`<!DOCTYPE html>\n<html lang="uz">\n<head>\n  <meta charset="UTF-8">\n  <title>Mening Saytim</title>\n</head>\n<body>\n  <h1>Salom Dunyo!</h1>\n  <p>Bu mening birinchi saytim.</p>\n</body>\n</html>`,
   homework:"5 xil heading (h1–h6), paragraf, va link qo'shing.",
   challenge:"'About Me' sahifasi yarating",
   quiz:{q:"HTML qisqartmasini to'liq yozing",opts:["HyperText Markup Language","High Tech Modern Language","Home Tool Markup Library"],ans:0}},
  {day:2,week:1,title:"HTML Teglar va Atributlar",tech:"HTML",
   lesson:"HTML teglar — &lt;p&gt;, &lt;a&gt;, &lt;img&gt;, &lt;div&gt;, &lt;span&gt;, &lt;ul&gt;, &lt;ol&gt;, &lt;li&gt; va boshqalar. Atributlar — href, src, class, id.",
   practice:"Barcha asosiy teglarni bir sahifada ishlating.",
   code:`<a href="https://google.com" target="_blank">Google</a>\n<img src="rasm.jpg" alt="Rasm tavsifi">\n<ul>\n  <li>Elementlar ro'yxati</li>\n  <li>Ikkinchi element</li>\n</ul>`,
   homework:"CV/Resume HTML versiyasini yozing (faqat HTML)",
   challenge:"Navigatsiya menyu (faqat HTML) yarating",
   quiz:{q:"Rasmni qo'shish uchun qaysi teg ishlatiladi?",opts:["<image>","<img>","<picture>"],ans:1}},
  {day:3,week:1,title:"Formalar va Input",tech:"HTML",
   lesson:"HTML formalar: &lt;form&gt;, &lt;input&gt;, &lt;textarea&gt;, &lt;select&gt;, &lt;button&gt;. Turi: text, email, password, checkbox, radio.",
   practice:"Login formasi, ro'yxatdan o'tish formasi yarating.",
   code:`<form action="/submit" method="POST">\n  <input type="text" placeholder="Ism" required>\n  <input type="email" placeholder="Email">\n  <input type="password" placeholder="Parol">\n  <button type="submit">Kirish</button>\n</form>`,
   homework:"To'liq Contact Us formasi yarating",
   challenge:"5 xil input turidagi forma",
   quiz:{q:"Forma ma'lumotlarini serverga yuborish uchun qaysi attribute kerak?",opts:["href","action","src"],ans:1}},
  {day:4,week:1,title:"Jadvallar va Semantik HTML",tech:"HTML",
   lesson:"&lt;table&gt;, &lt;tr&gt;, &lt;td&gt;, &lt;th&gt;, &lt;thead&gt;, &lt;tbody&gt;. Semantik: &lt;header&gt;, &lt;nav&gt;, &lt;main&gt;, &lt;section&gt;, &lt;article&gt;, &lt;footer&gt;.",
   practice:"5 ustunli jadval, semantik tuzilishli sahifa.",
   code:`<table>\n  <thead><tr><th>Ism</th><th>Yosh</th></tr></thead>\n  <tbody><tr><td>Ali</td><td>22</td></tr></tbody>\n</table>`,
   homework:"Klass jadvali yarating (7 kun, 6 dars)",
   challenge:"Semantik HTML bilan 1-sahifa layout",
   quiz:{q:"Semantik HTML qaysi teg emas?",opts:["<nav>","<div>","<main>"],ans:1}},
  {day:5,week:1,title:"HTML Multimedia",tech:"HTML",
   lesson:"Video, audio, iframe qo'shish. Favicons, meta teglar, Open Graph.",
   practice:"YouTube videoni embed qiling, audio player.",
   code:`<video src="video.mp4" controls width="100%"></video>\n<audio src="music.mp3" controls></audio>\n<iframe src="https://youtube.com/..." width="560" height="315"></iframe>`,
   homework:"Media bilan to'liq sahifa yarating",
   challenge:"YouTube embed + audio + gallery",
   quiz:{q:"Video qo'shish uchun qaysi teg?",opts:["<media>","<video>","<film>"],ans:1}},
  {day:6,week:1,title:"1-Hafta Loyihasi — Statik Sayt",tech:"HTML",
   lesson:"Bu kun barcha o'rganganlaringizni birlashtirish. Bitta to'liq statik sayt yarating.",
   practice:"Personal portfolio sahifasi: Header, About, Skills, Contact.",
   code:`<!-- Portfolio tuzilishi -->\n<header><nav>...</nav></header>\n<main>\n  <section id="about">...</section>\n  <section id="skills">...</section>\n  <section id="contact">...</section>\n</main>\n<footer>...</footer>`,
   homework:"Saytni GitHub Pages'ga deploy qiling",
   challenge:"Navigationda smooth scroll qiling",
   quiz:{q:"GitHub Pages nima uchun ishlatiladi?",opts:["Kod yozish","Bepul hosting","Dizayn qilish"],ans:1}},
  {day:7,week:1,title:"1-Hafta Imtihoni",tech:"HTML",
   lesson:"1-hafta barcha bilimlarini tekshirish. HTML quiz + kod yozish.",
   practice:"Berilgan dizaynga qarab HTML koding yarating.",
   code:`<!-- 1-hafta imtihon topshirig'i -->\n<!-- Vazifa: Restaurant menu sahifasi yarating -->\n<!-- Kerakli: header, nav, jadval, forma, footer -->`,
   homework:"Imtihon natijalarini GitHub'ga push qiling",
   challenge:"Accessibility: alt teglar, ARIA labels qo'shing",
   quiz:{q:"DOCTYPE deklaratsiyasi nima?",opts:["CSS fayli","HTML versiyasini bildiradi","JavaScript kodi"],ans:1}},
  {day:8,week:2,title:"CSS Bilan Tanishuv",tech:"CSS",
   lesson:"CSS (Cascading Style Sheets) — HTMLga ko'rinish beradi. Selectors, properties, values. Inline, Internal, External CSS.",
   practice:"HTMLga CSS qo'shing: colors, fonts, backgrounds.",
   code:`body {\n  font-family: Arial, sans-serif;\n  background-color: #f5f5f5;\n  margin: 0;\n}\nh1 {\n  color: #333;\n  font-size: 2.5rem;\n  text-align: center;\n}`,
   homework:"Kecha yaratgan HTML saytga CSS qo'shing",
   challenge:"Custom color palette — 5 rang tanlang",
   quiz:{q:"CSS qaysi teg ichida ulanadi?",opts:["<body>","<head>","<html>"],ans:1}},
  {day:9,week:2,title:"Box Model va Padding/Margin",tech:"CSS",
   lesson:"CSS Box Model: content, padding, border, margin. Width, height, box-sizing. Display: block, inline, inline-block.",
   practice:"Box model bilan kartochkalar yarating.",
   code:`.card {\n  width: 300px;\n  padding: 20px;\n  margin: 16px auto;\n  border: 2px solid #ddd;\n  border-radius: 10px;\n  box-sizing: border-box;\n  background: white;\n  box-shadow: 0 4px 12px rgba(0,0,0,0.1);\n}`,
   homework:"3 ta product card yarating",
   challenge:"Border-radius bilan kreativ dizayn",
   quiz:{q:"Box-sizing: border-box nimani anglatadi?",opts:["Faqat content o'lchamini hisoblaydi","Padding va border o'lchamga kiritiladi","Marginni olib tashlaydi"],ans:1}},
  {day:10,week:2,title:"Flexbox",tech:"CSS",
   lesson:"Flexbox — 1 o'lchamli layout. display:flex, justify-content, align-items, flex-wrap, gap, flex-grow.",
   practice:"Navbar, cards row, centering elements.",
   code:`.navbar {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  padding: 16px 32px;\n  background: #1a1a2e;\n}\n.cards {\n  display: flex;\n  gap: 16px;\n  flex-wrap: wrap;\n}`,
   homework:"Flexbox bilan to'liq navigatsiya yarating",
   challenge:"3 ustunli features section",
   quiz:{q:"justify-content: center nima qiladi?",opts:["Vertikal markazlaydi","Gorizontal markazlaydi","Elementlarni kengaytiradi"],ans:1}},
  {day:11,week:2,title:"CSS Grid",tech:"CSS",
   lesson:"CSS Grid — 2 o'lchamli layout. display:grid, grid-template-columns, grid-template-rows, gap, grid-area.",
   practice:"Gallery, dashboard, blog layout.",
   code:`.gallery {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 16px;\n}\n.hero {\n  display: grid;\n  grid-template-columns: 1fr 1fr;\n  align-items: center;\n  min-height: 100vh;\n}`,
   homework:"5 ustunli photo gallery yarating",
   challenge:"CSS Grid bilan newspaper layout",
   quiz:{q:"repeat(3, 1fr) nimani anglatadi?",opts:["3 ta teng ustun","3 ta satr","3px gap"],ans:0}},
  {day:12,week:2,title:"Responsive Design",tech:"CSS",
   lesson:"Media queries, mobile-first, viewport units (vw, vh, rem, em). Responsive images, hamburger menu.",
   practice:"Saytni mobile'da ham chiroyli ko'rinishga keltiring.",
   code:`.container {\n  width: 100%;\n  padding: 0 16px;\n}\n@media (min-width: 768px) {\n  .container {\n    max-width: 1200px;\n    margin: 0 auto;\n    padding: 0 32px;\n  }\n}`,
   homework:"Bitta saytni 3 xil o'lcham uchun responsive qiling",
   challenge:"Pure CSS hamburger menu",
   quiz:{q:"Mobile-first yondashuvi nima?",opts:["Avval mobile dizayn, keyin kattalashtirish","Avval desktop, keyin kichraytirish","Faqat mobile uchun"],ans:0}},
  {day:13,week:2,title:"CSS Animatsiyalar",tech:"CSS",
   lesson:"CSS transitions, animations, @keyframes, transform. Hover effektlar, loading animatsiyalar.",
   practice:"Button hover, fade in, slide, bounce animatsiyalar.",
   code:`@keyframes fadeIn {\n  from { opacity: 0; transform: translateY(20px); }\n  to   { opacity: 1; transform: translateY(0); }\n}\n.hero { animation: fadeIn 0.8s ease; }\n\n.btn {\n  transition: all 0.3s ease;\n}\n.btn:hover {\n  transform: translateY(-3px);\n  box-shadow: 0 10px 20px rgba(0,0,0,0.2);\n}`,
   homework:"4 xil animatsiyali element yarating",
   challenge:"CSS only loading spinner",
   quiz:{q:"transition property nima qiladi?",opts:["Animatsiya yaratadi","O'zgarishni silliq qiladi","Elementni ko'chadi"],ans:1}},
  {day:14,week:2,title:"2-Hafta Loyihasi — Barber Shop",tech:"CSS",
   lesson:"HTML + CSS bilimlarini birlashtirish. Professional Barber Shop website yarating.",
   practice:"Header, hero, services, gallery, contact section bilan to'liq sayt.",
   code:`:root {\n  --primary: #c9a84c;\n  --dark: #1a1a1a;\n  --light: #f5f0eb;\n}\n.hero {\n  min-height: 100vh;\n  background: linear-gradient(135deg, var(--dark), #2d2d2d);\n  display: grid;\n  place-items: center;\n}`,
   homework:"Saytni Netlify'ga deploy qiling",
   challenge:"Parallax scroll effekti qo'shing",
   quiz:{q:"CSS variables qanday e'lon qilinadi?",opts:["@variable: #fff","--variable: #fff","var: #fff"],ans:1}},
  {day:15,week:3,title:"JavaScript Asoslari",tech:"JavaScript",
   lesson:"JS nima, variables (let, const, var), data types (string, number, boolean, null, undefined, array, object).",
   practice:"Browser console'da code yozing.",
   code:`let ism = "Ali";\nconst yosh = 25;\nlet online = true;\n\nlet mevalar = ["olma", "nok", "banan"];\n\nlet user = {\n  name: "Ali",\n  age: 25,\n  city: "Toshkent"\n};\nconsole.log(user.name);`,
   homework:"10 xil variable va 2 xil object yarating",
   challenge:"O'zingiz haqida JSON object",
   quiz:{q:"const bilan e'lon qilingan o'zgaruvchini o'zgartirsa bo'ladimi?",opts:["Ha","Yo'q","Ba'zan"],ans:1}},
  {day:16,week:3,title:"Functions va Shart Operatorlari",tech:"JavaScript",
   lesson:"Functions, arrow functions, if/else, ternary operator, switch, loops (for, while, forEach).",
   practice:"Salom beruvchi funksiya, raqam tekshiruvi.",
   code:`const salom = (ism) => {\n  if (!ism) return "Ism kiriting!";\n  return \`Salom, \${ism}!\`;\n};\n\n[1,2,3,4,5].forEach(n => {\n  console.log(n % 2 === 0 ? "juft" : "toq");\n});`,
   homework:"Kalkulator funksiyalari yarating",
   challenge:"FizzBuzz — 1 dan 100 gacha",
   quiz:{q:"Arrow function qanday yoziladi?",opts:["function=>()","()=>{}","->()"],ans:1}},
  {day:17,week:3,title:"DOM Manipulation",tech:"JavaScript",
   lesson:"Document Object Model. getElementById, querySelector, innerHTML, textContent, style, classList.",
   practice:"HTML elementlarini JS orqali o'zgartiring.",
   code:`const btn = document.querySelector('#myBtn');\nconst title = document.getElementById('title');\n\ntitle.textContent = "Yangi nom";\nbtn.style.backgroundColor = "#00d4ff";\nbtn.classList.add("active");\n\nbtn.addEventListener('click', () => {\n  alert("Bosildi!");\n});`,
   homework:"Tugma bossangiz rang o'zgaruvchi element",
   challenge:"Dark/Light mode toggle",
   quiz:{q:"querySelector('#btn') nima qaytaradi?",opts:["Barcha #btn elementlar","Birinchi #btn element","String"],ans:1}},
  {day:18,week:3,title:"Events va Forms",tech:"JavaScript",
   lesson:"Event listeners: click, keydown, submit, mouseover, change. Form validation, preventDefault.",
   practice:"Form validation — bo'sh qoldirilmaydi.",
   code:`const form = document.querySelector('form');\n\nform.addEventListener('submit', (e) => {\n  e.preventDefault();\n  const email = document.querySelector('#email').value;\n  if (!email.includes('@')) {\n    alert("Noto'g'ri email!");\n    return;\n  }\n  console.log("Yuborildi:", email);\n});`,
   homework:"To'liq form validation (ism, email, parol)",
   challenge:"Real-time parol kuchini tekshiruv",
   quiz:{q:"preventDefault() nima qiladi?",opts:["Event'ni o'chiradi","Standart amalni bekor qiladi","Element'ni yashiradi"],ans:1}},
  {day:19,week:3,title:"LocalStorage",tech:"JavaScript",
   lesson:"LocalStorage, SessionStorage. setItem, getItem, removeItem, JSON.stringify, JSON.parse.",
   practice:"Todo list — localStorage'da saqlash.",
   code:`localStorage.setItem('user', JSON.stringify({name:'Ali'}));\n\nconst user = JSON.parse(localStorage.getItem('user'));\nconsole.log(user.name);\n\nlocalStorage.removeItem('user');\nlocalStorage.clear();`,
   homework:"To-Do List app — localStorage bilan",
   challenge:"Dark mode preference saqlash",
   quiz:{q:"localStorage'dagi ma'lumot qachon o'chadi?",opts:["Brauzer yopilganda","Foydalanuvchi o'chirguncha","1 soatdan keyin"],ans:1}},
  {day:20,week:3,title:"API va Fetch",tech:"JavaScript",
   lesson:"fetch() bilan ma'lumot olish, Promise, async/await, JSON parse qilish.",
   practice:"Bepul API'dan ma'lumot olish va ko'rsatish.",
   code:`async function getJoke() {\n  try {\n    const res = await fetch('https://api.chucknorris.io/jokes/random');\n    const data = await res.json();\n    document.querySelector('#joke').textContent = data.value;\n  } catch (err) {\n    console.error('Xato:', err);\n  }\n}\n\ngetJoke();`,
   homework:"Weather API bilan ob-havo sahifasi",
   challenge:"GitHub user profil qidirish",
   quiz:{q:"async/await nima uchun ishlatiladi?",opts:["CSS animatsiyasi","Asinxron kodni sinxron ko'rinishda yozish","Tez yuklash"],ans:1}},
  {day:21,week:3,title:"3-Hafta Imtihoni",tech:"JavaScript",
   lesson:"JavaScript barcha bilimlarini birlashtirish: DOM, Events, LocalStorage, Fetch.",
   practice:"Bitta to'liq interactive web app yarating.",
   code:`// Quiz App yarating\n// Talablar:\n// - 5 ta savol\n// - To'g'ri/Noto'g'ri tekshiruv\n// - Natija ko'rsatish\n// - LocalStorage'da yuqori natija saqlash`,
   homework:"Quiz App'ni GitHub'ga push qiling",
   challenge:"Timer qo'shing — 60 soniya limit",
   quiz:{q:"fetch() nima qaytaradi?",opts:["String","Promise","Array"],ans:1}},
  {day:22,week:4,title:"Git va GitHub",tech:"Git",
   lesson:"Git — version control. init, add, commit, push, pull, branch, merge. GitHub — cloud repository.",
   practice:"Birinchi repository yarating va push qiling.",
   code:`git init\ngit add .\ngit commit -m "Birinchi commit"\ngit remote add origin https://github.com/username/repo.git\ngit push -u origin main\n\ngit checkout -b yangi-feature\ngit merge yangi-feature`,
   homework:"Barcha oldingi loyihalarni GitHub'ga yuklang",
   challenge:"GitHub Pages orqali deploy",
   quiz:{q:"git commit nima qiladi?",opts:["Fayllarni o'chiradi","O'zgarishlarni saqlaydi","Server'ga yuboradi"],ans:1}},
  {day:23,week:4,title:"Tailwind CSS",tech:"Tailwind",
   lesson:"Tailwind — utility-first CSS framework. Class bilan tez dizayn. CDN va NPM orqali ulash.",
   practice:"HTML'ga Tailwind CDN qo'shing va qayta dizayn qiling.",
   code:`<!-- Tailwind CDN -->\n<script src="https://cdn.tailwindcss.com"><\/script>\n\n<div class="min-h-screen bg-gray-900 flex items-center justify-center">\n  <div class="bg-white rounded-2xl p-8 shadow-xl">\n    <h1 class="text-3xl font-bold text-gray-900 mb-4">Salom!</h1>\n    <button class="mt-4 bg-blue-500 hover:bg-blue-600 text-white px-6 py-2 rounded-lg">\n      Bosing\n    </button>\n  </div>\n</div>`,
   homework:"Tailwind bilan login sahifasi",
   challenge:"Dark mode Tailwind bilan",
   quiz:{q:"Tailwind CDN qayerdan yuklanadi?",opts:["tailwind.com","cdn.tailwindcss.com","npmjs.com"],ans:1}},
  {day:24,week:4,title:"VS Code Tips va Tricks",tech:"Tools",
   lesson:"VS Code shortcuts, extensions, Emmet, multi-cursor, integrated terminal, Live Server, Prettier, GitLens.",
   practice:"Top 10 VS Code shortcut'ni mashq qiling.",
   code:`// VS Code shortcuts\n// Ctrl+P — Fayl qidirish\n// Ctrl+Shift+P — Command palette\n// Alt+Click — Multi cursor\n// Ctrl+D — Keyingi mos so'zni tanlash\n// Ctrl+/ — Comment toggle\n// Alt+Shift+F — Format code\n// Ctrl+\` — Terminal ochish\n// Ctrl+B — Sidebar yashirish`,
   homework:"Live Server + Prettier extension o'rnating",
   challenge:"Snippet yarating — HTML boilerplate",
   quiz:{q:"Emmet nima?",opts:["HTML framework","Kod qisqartma tizimi","CSS library"],ans:1}},
  {day:25,week:4,title:"Netlify Deployment",tech:"Deployment",
   lesson:"Static saytni deploy qilish. Netlify, Vercel, GitHub Pages. Domain ulash, SSL, CDN.",
   practice:"Netlify'ga drag-and-drop deploy.",
   code:`npm install -g netlify-cli\nnetlify login\nnetlify init\nnetlify deploy --prod\n\n# netlify.toml\n[build]\n  publish = "dist"\n  command = "npm run build"`,
   homework:"2 ta saytni Netlify'ga deploy qiling",
   challenge:"Custom domain ulang",
   quiz:{q:"Netlify nima uchun ishlatiladi?",opts:["Kod yozish","Bepul web hosting","Database"],ans:1}},
  {day:26,week:4,title:"SEO Asoslari",tech:"HTML",
   lesson:"Meta teglar, title, description, Open Graph, sitemap, robots.txt, semantic HTML, page speed.",
   practice:"Saytingizga to'liq SEO meta teglar qo'shing.",
   code:`<head>\n  <title>Barber Shop — Toshkent | Professional</title>\n  <meta name="description" content="Toshkentdagi eng yaxshi barber shop.">\n  <meta property="og:title" content="Barber Shop Toshkent">\n  <meta property="og:image" content="/og-image.jpg">\n  <meta property="og:url" content="https://barbershop.uz">\n</head>`,
   homework:"Saytingizni Google PageSpeed bilan test qiling",
   challenge:"sitemap.xml va robots.txt yarating",
   quiz:{q:"meta description nimani aniqlaydi?",opts:["Sahifa tegi","Qidiruvdagi tavsif","Font"],ans:1}},
  {day:27,week:4,title:"Portfolio Yaratish",tech:"All",
   lesson:"Professional portfolio sayt — xizmat sotishning asosiy qurol. Tuzilma, kontentni yozish, loyihalarni ko'rsatish.",
   practice:"To'liq portfolio sayt yarating: About, Projects, Contact.",
   code:`.portfolio-layout {\n  display: grid;\n  grid-template-areas:\n    "hero hero"\n    "about skills"\n    "projects projects"\n    "contact contact";\n  gap: 0;\n}\n\n.project-card:hover {\n  transform: translateY(-8px);\n  box-shadow: 0 20px 40px rgba(0,0,0,0.2);\n}`,
   homework:"Portfolio'ni Netlify'ga deploy qiling va URL saqlab qo'ying",
   challenge:"Dark mode + smooth animations",
   quiz:{q:"Portfolio'da eng muhim nima?",opts:["Ko'p animatsiya","Real loyihalar","Ko'p sahifa"],ans:1}},
  {day:28,week:4,title:"Fiverr Profile Ochish",tech:"Freelance",
   lesson:"Fiverr'da professional profil: bio, skills, portfolio, gig yaratish, narx belgilash.",
   practice:"Fiverr'ga ro'yxatdan o'ting va birinchi Gig yarating.",
   code:`// Fiverr Gig Sarlavhasi formulasi:\n// "I will create a [NIMA] for [KIM] that [NATIJA]"\n\n// Misol:\n"I will create a professional restaurant website\nfor small businesses that attracts customers"\n\n// Narx:\n// Basic: $30 — 1 sahifa, 3 kun\n// Standard: $80 — 5 sahifa, 7 kun\n// Premium: $200 — 10 sahifa, 14 kun`,
   homework:"Birinchi Gig'ni publish qiling",
   challenge:"3 portfolio screenshot tayyorlang",
   quiz:{q:"Fiverr'da xizmat narxini nima belgilaydi?",opts:["Faqat Gig title","Portfolyo, reyting va tavsif","Faqat reyting"],ans:1}},
  {day:29,week:4,title:"Klient Topish Strategiyasi",tech:"Freelance",
   lesson:"Telegram, Instagram, LinkedIn orqali klient topish. Cold outreach, referral, local businesses.",
   practice:"5 ta potensial klientga xabar yuboring.",
   code:`// Telegram xabar shabloni:\n\n"Salom! Men veb-dasturchi,\nsizning biznesingiz uchun professional\nwebsite yarataman.\n\n✅ Mobile friendly\n✅ Tez yuklaydi\n✅ SEO optimized\n\nNarx: $50 dan boshlanadi.\nNamunalar: [portfolio link]"`,
   homework:"10 ta mahalliy biznesni aniqlang va saytlari bor-yo'qligini tekshiring",
   challenge:"Instagram portfolio page yarating",
   quiz:{q:"Eng tez klient topish usuli?",opts:["Cold email","Do'stlar va tanishlar orqali referral","Reklama"],ans:1}},
  {day:30,week:4,title:"YAKUNIY KUN — 🎉 Graduation!",tech:"All",
   lesson:"30 kunlik kursni yakunladingiz! Endi siz HTML, CSS, JavaScript, Git va deployment'ni bilasiz.",
   practice:"Birinchi to'liq freelance loyihangizni yarating va deploy qiling.",
   code:`// 30 kunlik sayohatingiz:\n// HTML    ✅ — 7 kun\n// CSS     ✅ — 7 kun\n// JS      ✅ — 7 kun\n// Pro     ✅ — 9 kun\n\n// Keyingi qadamlar:\n// React.js\n// Node.js\n// TypeScript\n// Figma\n\nconsole.log("Tabriklayman! 🎉");`,
   homework:"Birinchi Fiverr buyurtmangizni oling 💪",
   challenge:"React.js ni o'rganishni boshlang",
   quiz:{q:"Keyingi qadam nima?",opts:["To'xtash","React va Node.js o'rganish","Qayta boshlash"],ans:1}}
];

const PROJECTS = [
  {name:"Instagram Login Page",emoji:"📸",banner:"linear-gradient(135deg,#833ab4,#fd1d1d,#fcb045)",desc:"Instagram uslubida chiroyli login sahifasi. Glassmorphism va gradient bilan.",tags:["HTML","CSS","Flexbox"],difficulty:"d-easy",dlabel:"Oson",points:["Markazlangan login forma","CSS glassmorphism","Gradient background","Password show/hide"]},
  {name:"Barber Shop Website",emoji:"💈",banner:"linear-gradient(135deg,#1a1a2e,#c9a84c)",desc:"Professional sartaroshxona sayt. Services, gallery, booking forma bilan.",tags:["HTML","CSS","Grid","JS"],difficulty:"d-medium",dlabel:"O'rta",points:["Hero section + CTA","Services cards","Photo gallery","Contact forma"]},
  {name:"Car Showroom",emoji:"🚗",banner:"linear-gradient(135deg,#0f0f0f,#e74c3c)",desc:"Zamonaviy avtosalon landing page. 3D card effektlar, slideshow bilan.",tags:["HTML","CSS","Animations","JS"],difficulty:"d-medium",dlabel:"O'rta",points:["Hero with car image","Models showcase","3D card hover","Price table"]},
  {name:"Gaming Landing Page",emoji:"🎮",banner:"linear-gradient(135deg,#0f0c29,#302b63,#24243e)",desc:"Futuristic gaming sayt. Neon effektlar, animatsiyalar va CTA bilan.",tags:["HTML","CSS","JS","Animations"],difficulty:"d-hard",dlabel:"Qiyin",points:["Neon glow effects","Animated hero","Features section","Countdown timer"]},
  {name:"Portfolio Website",emoji:"💼",banner:"linear-gradient(135deg,#00b09b,#96c93d)",desc:"Professional developer portfolio. Skills, projects, contact forma bilan.",tags:["HTML","CSS","JS","Tailwind"],difficulty:"d-medium",dlabel:"O'rta",points:["Animated hero","Skills progress bars","Projects grid","Contact form"]},
  {name:"Restaurant Website",emoji:"🍽️",banner:"linear-gradient(135deg,#f7971e,#ffd200)",desc:"Restoran uchun premium veb sayt. Menu, gallery, reservation forma.",tags:["HTML","CSS","JS","Responsive"],difficulty:"d-hard",dlabel:"Qiyin",points:["Full-screen hero","Interactive menu","Image gallery","Table booking"]}
];

const TOOLS = [
  {icon:"💻",name:"VS Code",why:"Eng ommabop, bepul kod muharrir. Extensions, debugging, terminal.",install:"code.visualstudio.com dan yuklab o'rnating",use:"Live Server, Prettier, GitLens extensionlarini o'rnating"},
  {icon:"🐙",name:"GitHub",why:"Kod saqlash, portfolio, hamkorlik va version control uchun",install:"github.com da ro'yxatdan o'ting",use:"git init, add, commit, push buyruqlari bilan ishlang"},
  {icon:"🎨",name:"Figma",why:"UI/UX dizayn qilish. Saytni kodlashdan avval vizual loyiha",install:"figma.com da bepul hisob oching",use:"Frames, components, auto-layout o'rganing"},
  {icon:"🖌️",name:"Canva",why:"Logo, banner, social media uchun grafika yaratish",install:"canva.com — brauzerda ishlaydi",use:"Templates ishlatib tez professional grafika"},
  {icon:"🚀",name:"Netlify",why:"Bepul statik sayt hosting, avtomatik deploy, SSL",install:"netlify.com da ro'yxatdan o'ting",use:"Drag-drop deploy yoki GitHub bilan integratsiya"},
  {icon:"▲",name:"Vercel",why:"Next.js va React proyektlar uchun eng yaxshi hosting",install:"vercel.com da GitHub orqali kiring",use:"vercel deploy buyrug'i yoki GitHub push bilan auto-deploy"}
];

const RESOURCES = [
  {icon:"🌐",bg:"#f16529",name:"W3Schools",desc:"HTML, CSS, JS uchun interaktiv qo'llanma va reference. Yangi boshlovchilar uchun ideal.",url:"https://w3schools.com"},
  {icon:"📖",bg:"#000",name:"MDN Web Docs",desc:"Mozilla'ning rasmiy veb dokumentatsiyasi. Eng to'liq va ishonchli manba.",url:"https://developer.mozilla.org"},
  {icon:"🏕️",bg:"#006400",name:"freeCodeCamp",desc:"Bepul, sertifikatli 300+ soatlik kurslar. Loyihalar bilan amaliy o'rganish.",url:"https://freecodecamp.org"},
  {icon:"🎬",bg:"#333",name:"Traversy Media",desc:"YouTube'da 500+ bepul darslar. Brad Traversy — eng yaxshi web dev o'qituvchi.",url:"https://youtube.com/@TraversyMedia"},
  {icon:"📺",bg:"#ff0000",name:"SuperSimpleDev",desc:"JavaScript va HTML/CSS darslarini juda oddiy tushuntiradigan kanal.",url:"https://youtube.com/@SuperSimpleDev"},
  {icon:"🧑‍💻",bg:"#1a1a2e",name:"CSS Tricks",desc:"CSS tricks, tips va complete guides. Flexbox va Grid'ning eng yaxshi manba.",url:"https://css-tricks.com"}
];

const EXAMS = [
  {week:"HAFTA 1",title:"HTML Imtihoni",desc:"HTML asoslari — semantik tuzilish, formalar, jadvallar",items:["Test: 20 ta savol (HTML tags, attributes, forms)","Amaliy: Restaurant menu HTML sahifasi","Kod: Berilgan dizaynga qarab HTML yozing","Bonus: Accessibility — ARIA labels qo'shing"]},
  {week:"HAFTA 2",title:"CSS Imtihoni",desc:"CSS, Flexbox, Grid, Responsive, Animatsiyalar",items:["Test: 25 ta savol (selectors, box model, flexbox, grid)","Amaliy: Barber Shop dizayn","Kod: Responsive navbar yarating","Bonus: Pure CSS animatsiya — loader"]},
  {week:"HAFTA 3",title:"JavaScript Imtihoni",desc:"JS asoslari, DOM, Events, LocalStorage, Fetch",items:["Test: 25 ta savol (functions, DOM, events)","Amaliy: Interactive Quiz App","Kod: Todo app localStorage bilan","Bonus: GitHub API bilan user search"]},
  {week:"HAFTA 4 — FINAL",title:"Yakuniy Imtihon",desc:"Barcha bilimlar — to'liq portfolio loyiha",items:["Test: 30 ta savol (barcha texnologiyalar)","Amaliy: To'liq biznes landing page","Deploy: Netlify'ga chiqaring","Bonus: Fiverr gig yarating va portfolio URLni yuboring"]}
];

const FREELANCE_STEPS = [
  {icon:"📋",title:"Portfolio Tayyorlash",num:"01",desc:"Minimum 3 ta namuna loyiha. GitHub'ga yuklang. Netlify'da jonlantiring. Har bir loyiha uchun screenshot oling."},
  {icon:"🐟",title:"Fiverr Account Ochish",num:"02",desc:"Professional profil rasmi (50$+ haftalik daromad uchun muhim). Bio yozing, skills qo'shing, portfolio yuklang."},
  {icon:"🎯",title:"Birinchi Gig Yaratish",num:"03",desc:"'I will create a professional website' — aniq tavsif, 3 package (Basic/Standard/Premium), 10+ tag."},
  {icon:"📨",title:"Telegram Marketing",num:"04",desc:"Biznes guruhlarda e'lon bering. Local restoran, salon, magazinlarga shaxsan murojaat qiling."},
  {icon:"⭐",title:"Birinchi Buyurtmani Olish",num:"05",desc:"Birinchi 3 ta ish uchun narxni arzonroq qiling (revyu olish uchun). 5 yulduzli baho olish eng muhim."},
  {icon:"💬",title:"Klientlar Bilan Ishlash",num:"06",desc:"Doim tez javob bering. Muddatni bajaring. Bonus xizmat ko'rsating. Referral so'rang."},
  {icon:"📈",title:"Narxni Ko'tarish",num:"07",desc:"10 muvaffaqiyatli loyihadan keyin narxni oshiring. Portfolio kuchli bo'lsa $100–300+ olish mumkin."},
  {icon:"🌟",title:"Brendingizni Quring",num:"08",desc:"Telegram kanal oching. Instagram'da ish namunalari yuboring. LinkedIn profil yarating."}
];
